// <auto-generated />
namespace Peon.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddChildren : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddChildren));
        
        string IMigrationMetadata.Id
        {
            get { return "201604130830556_AddChildren"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
